# top movies on imdb in 2026

## rating tertinggi berdasarkan Imdb

menghitung film dengan rating tertinggi

In [2]:
import pandas as pd
import numpy as np
import ast
import io

df =pd.read_csv('data_analyst_top_movies_cleaned.csv')
df.sort_values(
    by=['averageRating'],
    ascending=False
)[['primaryTitle', 'Year', 'averageRating','metascore', 'numVotes']].head(10)

,primaryTitle,Year,averageRating,metascore,numVotes
0,The Shawshank Redemption,1994,9.3,82.0,3219026
1,The Godfather,1972,9.2,100.0,2244201
2,The Dark Knight,2008,9.1,85.0,3204629
3,The Godfather Part II,1974,9.0,90.0,1505420
4,The Lord of the Rings: The Return of the King,2003,9.0,94.0,2181632
5,12 Angry Men,1957,9.0,97.0,996035
6,Schindler's List,1993,9.0,95.0,1595817
7,The Lord of the Rings: The Fellowship of the Ring,2001,8.9,92.0,2224790
106,Attack on Titan: The Last Attack,2024,8.9,85.0,34139
8,Pulp Fiction,1994,8.8,95.0,2455116

## rating tertinggi berdasarkan metascore

In [4]:
df.sort_values(
    by=['metascore', 'numVotes'],
    ascending=False
)[['primaryTitle', 'Year', 'averageRating','metascore', 'numVotes']].head(10)

            primaryTitle  Year  averageRating  metascore  numVotes
1          The Godfather  1972            9.2      100.0   2244201
46            Casablanca  1942            8.5      100.0    658490
51           Rear Window  1954            8.4      100.0    571660
117         Citizen Kane  1941            8.2      100.0    495133
116              Vertigo  1958            8.2      100.0    461004
100   Lawrence of Arabia  1962            8.3      100.0    344195
221          Tokyo Story  1953            8.1      100.0     78394
88   Singin' in the Rain  1952            8.3       99.0    284620
55           City Lights  1931            8.5       99.0    217547
155      Pan's Labyrinth  2006            8.2       98.0    750575

## vote terbanyak

menghitung film dengan jumlah vote terbanyak

In [14]:
df.sort_values(
    by='numVotes',
    ascending=False
)[['primaryTitle', 'Year', 'averageRating', 'metascore','numVotes']].head(10)

,primaryTitle,Year,averageRating,metascore,numVotes
0,The Shawshank Redemption,1994,9.3,82.0,3219026
2,The Dark Knight,2008,9.1,85.0,3204629
13,Inception,2010,8.8,74.0,2849077
12,Fight Club,1999,8.8,67.0,2641980
16,Interstellar,2014,8.7,74.0,2579990
11,Forrest Gump,1994,8.8,82.0,2519721
8,Pulp Fiction,1994,8.8,95.0,2455116
15,The Matrix,1999,8.7,73.0,2266147
1,The Godfather,1972,9.2,100.0,2244201
7,The Lord of the Rings: The Fellowship of the Ring,2001,8.9,92.0,2224790

## jumlah genre terbanyak

menghitung jumlah genre film terbanyak

In [15]:
def parse_genres(value):
    if pd.isna(value):
        return []
    
    # Jika sudah berupa list
    if isinstance(value, list):
        return value
    
    # Jika berupa string
    if isinstance(value, str):
        try:
            result = ast.literal_eval(value)
            
            if isinstance(result, list):
                return result
            
            return [str(result)]
        
        except (ValueError, SyntaxError):
            # Jika format bukan Python list,
            # pisahkan berdasarkan koma
            return [x.strip() for x in value.split(',') if x.strip()]
    
    return []

In [16]:
df['genres'] = df['genres'].apply(parse_genres)
df[['primaryTitle', 'genres']].head(10)

,primaryTitle,genres
0,The Shawshank Redemption,[Drama]
1,The Godfather,"[Crime, Drama]"
2,The Dark Knight,"[Crime, Thriller]"
3,The Godfather Part II,"[Crime, Drama]"
4,The Lord of the Rings: The Return of the King,"[Adventure, Drama, Fantasy]"
5,12 Angry Men,"[Crime, Drama]"
6,Schindler's List,"[Biography, Drama, History]"
7,The Lord of the Rings: The Fellowship of the Ring,"[Adventure, Drama, Fantasy]"
8,Pulp Fiction,"[Crime, Drama]"
9,"The Good, the Bad and the Ugly","[Adventure, Drama, Western]"

In [17]:
genre_df = df[
    ['primaryTitle', 'genres', 'averageRating']
].explode('genres')
genre_counts = genre_df['genres'].value_counts()

genre_counts.head(10)

genres
Drama        179
Adventure     66
Crime         52
Comedy        42
Action        42
Mystery       31
Thriller      30
Animation     28
Biography     27
War           24
Name: count, dtype: int64

## rata rata rating berdasarkan genre

In [18]:
genre_rating = (
    genre_df
    .groupby('genres')['averageRating']
    .agg(['count', 'mean'])
    .sort_values('mean', ascending=False)
)
genre_rating.columns = ['Movie Count', 'Average Rating']

genre_rating_filtered = genre_rating[
    genre_rating['Movie Count'] >= 5
].sort_values(
    'Average Rating',
    ascending=False
)

genre_rating_filtered

           Movie Count  Average Rating
genres
Fantasy             18        8.416667
Western              6        8.400000
Crime               52        8.369231
Sci-Fi              22        8.354545
Horror               8        8.337500
Adventure           66        8.322727
Drama              179        8.320670
Thriller            30        8.320000
Action              42        8.304762
Romance             22        8.304545
Animation           28        8.292857
Mystery             31        8.287097
War                 24        8.270833
History              9        8.266667
Biography           27        8.259259
Family              12        8.258333
Comedy              42        8.226190
Sport                6        8.116667

## tahun dengan jumlah film terbanyak

### dihitung pertahun

In [19]:
movies_by_year = (
    df['Year']
    .value_counts()
    .sort_index()
)
movies_by_year.sort_values(
    ascending=False
).head(10)

Year
2004    8
1995    8
2003    7
1999    6
1957    6
2009    6
2019    6
1994    5
1975    5
2014    5
Name: count, dtype: int64

### dihitung per decade

In [20]:
df['decade'] = (
    (df['Year'] // 10) * 10
)
movies_by_decade = (
    df['decade']
    .value_counts()
    .sort_index()
)

movies_by_decade

decade
1920     6
1930     6
1940     9
1950    21
1960    17
1970    17
1980    26
1990    39
2000    48
2010    43
2020    18
Name: count, dtype: int64

## ringkasan

In [21]:
decade_summary = (
    df.groupby('decade')
    .agg(
        Movie_Count=('primaryTitle', 'count'),
        Average_Rating=('averageRating', 'mean'),
        Average_Runtime=('runtimeMinutes', 'mean'),
        Average_Votes=('numVotes', 'mean')
    )
    .round(2)
)

decade_summary

        Movie_Count  Average_Rating  Average_Runtime  Average_Votes
decade
1920              6            8.13            91.67      119790.50
1930              6            8.28           123.67      274393.33
1940              9            8.29           119.11      306782.11
1950             21            8.27           126.33      281723.52
1960             17            8.34           145.18      336388.65
1970             17            8.35           136.71      833957.41
1980             26            8.27           131.73      713155.62
1990             39            8.41           126.82     1219115.44
2000             48            8.32           136.65     1011680.94
2010             43            8.26           130.84      936846.74
2020             18            8.37           142.72      370798.56